# nginx proxy address - http://172.17.0.1:8087

name: lemmy
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  lemmy:
    image: dessalines/lemmy:latest
    pull_policy: always
    container_name: lemmy-app
    restart: always
    logging: *default-logging
    networks:
      - lemmy
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8087:8536"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: lemmy-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      LEMMY_DATABASE_URL: postgresql://${DB_USER_NAME:-lemmy}:${DB_USER_PASS:-changeme_db_password}@lemmy-db:5432/${DB_CREATE_DATABASE_NAME:-lemmy}
      RUST_LOG: warn
    volumes:
      - ./volumes/config/lemmy:/config
    depends_on:
      lemmy-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8536"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://lemmy-app:8536'
      - 'cloudflare.hostname=lemmy.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.lemmy-app.entrypoints=http'
      - 'traefik.http.routers.lemmy-app-secure.tls=true'
      - 'traefik.http.routers.lemmy-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.lemmy-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.lemmy-app.middlewares=lemmy-app-https-redirect'
      - 'traefik.http.routers.lemmy-app-secure.entrypoints=https'
      - 'traefik.http.routers.lemmy-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.lemmy-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.lemmy-app-secure.service=lemmy-app'
      - 'traefik.http.services.lemmy-app.loadbalancer.server.port=8536'

  lemmy-ui:
    image: dessalines/lemmy-ui:latest
    pull_policy: always
    container_name: lemmy-ui
    restart: always
    logging: *default-logging
    networks:
      - lemmy
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8088:1234"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: lemmy-ui
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy:8536
      LEMMY_UI_LEMMY_EXTERNAL_HOST: ${BASE_HOST_NAME:-$HOSTNAME}
      LEMMY_UI_HTTPS: true
    depends_on:
      - lemmy
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://lemmy-ui:1234'
      - 'cloudflare.hostname=lemmy.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.lemmy-ui.entrypoints=http'
      - 'traefik.http.routers.lemmy-ui-secure.tls=true'
      - 'traefik.http.routers.lemmy-ui.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.lemmy-ui-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.lemmy-ui.middlewares=lemmy-ui-https-redirect'
      - 'traefik.http.routers.lemmy-ui-secure.entrypoints=https'
      - 'traefik.http.routers.lemmy-ui-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.lemmy-ui-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.lemmy-ui-secure.service=lemmy-ui'
      - 'traefik.http.services.lemmy-ui.loadbalancer.server.port=1234'

  lemmy-db:
    image: postgres:latest
    pull_policy: always
    container_name: lemmy-db
    restart: always
    logging: *default-logging
    networks:
      - lemmy
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: lemmy-db
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-lemmy}
      POSTGRES_USER: ${DB_USER_NAME:-lemmy}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./volumes/data/db/postgres/lemmy:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lemmy:
    name: lemmy
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
