# nginx proxy address - http://172.17.0.1:8087

name: lemmy
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  lemmy:
    image: dessalines/lemmy:latest
    pull_policy: always
    container_name: lemmy-app
    restart: always
    logging: *default-logging
    networks:
      - lemmy
    ports:
      - "172.17.0.1:8087:8536"
    environment:
      TZ: ${TZ:-America/New_York}
      LEMMY_DATABASE_URL: postgresql://${DB_USER_NAME:-lemmy}:${DB_USER_PASS:-changeme_db_password}@lemmy-db:5432/${DB_CREATE_DATABASE_NAME:-lemmy}
      RUST_LOG: warn
    volumes:
      - ./volumes/config/lemmy:/config
    depends_on:
      lemmy-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8536"]
      interval: 30s
      timeout: 10s
      retries: 3

  lemmy-ui:
    image: dessalines/lemmy-ui:latest
    pull_policy: always
    container_name: lemmy-ui
    restart: always
    logging: *default-logging
    networks:
      - lemmy
    ports:
      - "172.17.0.1:8088:1234"
    environment:
      TZ: ${TZ:-America/New_York}
      LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy:8536
      LEMMY_UI_LEMMY_EXTERNAL_HOST: ${BASE_HOST_NAME:-$HOSTNAME}
      LEMMY_UI_HTTPS: true
    depends_on:
      - lemmy

  lemmy-db:
    image: postgres:latest
    pull_policy: always
    container_name: lemmy-db
    restart: always
    logging: *default-logging
    networks:
      - lemmy
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-lemmy}
      POSTGRES_USER: ${DB_USER_NAME:-lemmy}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./volumes/data/db/postgres/lemmy:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lemmy:
    name: lemmy
    external: false
